### ISSUE TITLE
BUG - Projects that are not approved are shown in projects.

### ISSUE THREAD

**Issue by abdelh17** [abdelh17/Quolance#113]
Steps to reproduce:
1. Create a project as a client.
2. The project is shown in the projects section.
3. Login as a freelancer.
4. Navigate to /projects
5. The created and not approved project is displayed.

Expected behaviour:
The project should not be visible in the projects section.

**Comment by Zakaria0907** [comment]
solved in backend

**Comment by abdelh17** [comment]
fixed in #145 by @Zakaria0907 in [FreelancerWorkflowServiceImpl.java](https://github.com/abdelh17/Quolance/blob/e3589f4662e28b0be788c54418cd2bed45ff4d59/quolance-api/src/main/java/com/quolance/quolance_api/services/business_workflow/impl/FreelancerWorkflowServiceImpl.java)
