### ISSUE TITLE
BE - Work on service for admin to approve/reject projects by client

### ISSUE THREAD

**Issue by abdelh17** [abdelh17/Quolance#33]
As an admin, I should be able to accept or decline a project depending on the guidelines. If the project violate the guidelines, it should be rejected. 
- IDEALLY (the admin receives a notifcation message in his email about a new contract posting)
- Make sure the status of a project is set to "pending approval" when created
- Change the status to approved/rejected. If rejected, need to have a message for reason.

**Comment by KA-devl** [comment]
@abdelh17 Added description for more context
