### ISSUE TITLE
FE - Make UI for creation/change of a user profile

### ISSUE THREAD

**Issue by abdelh17** [abdelh17/Quolance#58]
- [ ] Make the static page
- [ ] Connect to the backend

**Comment by abdelh17** [comment]
@Itek01 as discussed, this is not public profile, it is the user information. See with @ChemsCode

**Comment by Itek01** [comment]
> @Itek01 as discussed, this is not public profile, it is the user information. See with @ChemsCode

Sounds good

**Comment by abdelh17** [comment]
closed in #72
