### ISSUE TITLE
BE/FE - Authentication and Authorization Rework

### ISSUE THREAD

**Issue by ChemsCode** [abdelh17/Quolance#69]
### Description
The current authentication mechanism requires re-evaluation to enhance security, usability, and maintainability. The new approach aims to implement a more robust system that addresses identified limitations in token handling, session management, and user roles.

### Objectives
1. **Improve Security**: Implement OAuth 2.0 with JWT to securely manage tokens and user sessions.
2. **Role-Based Access Control (RBAC)**: Define and implement a flexible RBAC system to handle permissions more effectively.
3. **Token Expiry and Refresh**: Ensure secure handling of token expiry, with automatic refresh and seamless user experience.
4. **Documentation**: Update README with setup instructions for the new authentication system.

### Related Tasks:

[#72 ] - Auth Rework BE
[#78] -  Implemented Registration, Role-Based Access, and Profile Updates with Styling Fixes

**Comment by abdelh17** [comment]
associated to #3

**Comment by abdelh17** [comment]
#72 contains all the changed for this
